version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - '443:443'
    volumes:
      - wordpress:/var/www/html
    env_file:
      - ./.env
    networks:
      - mynet
    depends_on:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    volumes:
      - wordpress:/var/www/html
    env_file:
      - ./.env
    networks:
      - mynet
    depends_on:
      - mariadb

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - mynet

networks:
  mynet:
    name: mynet
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none' 
      device: '/home/zbouayya/data/wordpress'
      o: 'bind'

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none' 
      device: '/home/zbouayya/data/mariadb'
      o: 'bind'
